import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { Tajawal } from "next/font/google";

const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  variable: "--font-tajawal",
});
export const metadata = {
  title: "Pay Per View",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return children;
}