import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { routing } from "../../i18n/routing";
import { notFound } from "next/navigation";
import { ThemeProvider } from "@/context/ThemeContext";
import { MessagesProvider } from "@/context/MessagesContext";
import MessagesPanel from "@/components/MessagesPanel"; // 👈 استيراد مكون الرسائل

export const metadata = {
  title: "Pay Per View",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <ThemeProvider>
        <MessagesProvider>
          {children}
          <MessagesPanel />
        </MessagesProvider>
      </ThemeProvider>
    </NextIntlClientProvider>
  );
}